name = "learning-cloudflare-workers"
main = "src/index.ts"
compatibility_date = "2022-07-24"

[durable_objects]
bindings = [
	{ name = "limiters", class_name = "RateLimiterDurableObject" },
	{ name = "rooms", class_name = "ChatRoomDurableObject" },
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiterDurableObject", "ChatRoomDurableObject"]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false
